### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by heiyumiao** [hewei2001/campus-canteen-ordering#1]
大佬你好，这个程序能够移植到树莓派上呢？
如果可以，需要修改什么程序内容？
万分感谢！

**Comment by hewei2001** [comment]
您好，偏硬件的这些东西我不是很了解，也没有实践过，不敢妄加指点。

但是我觉得您可以从环境迁移（如 Python 依赖、MySQL 等）入手，以及一些网络接口等入手。

**Comment by heiyumiao** [comment]
谢谢解答，主要也不涉及硬件。只是整体环境变成linux。
目前django我已经移植好了，但是现在数据库这边有些问题，我看您用的是  “将 Powerdesigner 生成的 crebas.sql 打开并执行，注意要注释掉 drop 等语句。此时我们的数据库就建好了。”  这个文件我没有找到。
我能不使用Powerdesigner 建一个mysql的数据库文件吗？里面需要那些条目结构？
我这边的目标是能够运行网站，对于后台数据库文件要求不高。
万分感谢！

**Comment by heiyumiao** [comment]
![image](https://user-images.githubusercontent.com/45146867/161885909-1309c857-1f85-4705-b7ec-6bb90ad02dd3.png)
目前我运行这句python manage.py makemigrations，结果是连不上数据库

**Comment by heiyumiao** [comment]
已解决，谢谢。
刚发现再点击顾客注册--直接登录的时候会报404的错误，这个是没有设置内容吗

**Comment by hewei2001** [comment]
「将 Powerdesigner 生成的 crebas.sql 打开并执行」这句话其实是说给用 Powerdesigner 做实验的学弟学妹听的，因为我们实验是要先用这个创建数据库的雏形，然后再用 Django 反向导入。

在使用本项目的时候则无需 Powerdesigner，直接 Django 反向导入现成的就行。

**Comment by hewei2001** [comment]
「运行这句python manage.py makemigrations，结果是连不上数据库」、「再点击顾客注册--直接登录的时候会报404的错误」这两个应该都是你配置的步骤有问题导致的，你可以看看是不是漏掉了哪一步？因为最近有其他人找我，都是能成功配置好的。

**Comment by heiyumiao** [comment]
之前是数据库配置的问题，目前已经解决了，现在点单和后台等功能都可以使用了。
但是点击顾客注册--直接登录的时候还是会报404的错误
