### ISSUE TITLE
打扰了 谢谢

### ISSUE THREAD

**Issue by awantedboy** [hewei2001/campus-canteen-ordering#2]
解决了

**Comment by awantedboy** [comment]
![image](https://user-images.githubusercontent.com/55446040/172051857-7a1e262a-e803-48cb-8766-cc376c682731.png)

**Comment by awantedboy** [comment]
![image](https://user-images.githubusercontent.com/55446040/172051878-248dda0e-5773-4418-9fca-9636302951a0.png)

**Comment by hewei2001** [comment]
不好意思，最近太忙了没来得及看，希望这个项目对您有帮助！
