### ISSUE TITLE
请问可以提供一下数据吗，真的非常感谢，不太清楚“本项目是建立在之前的实验结果的基础（已经用 PowerDesigner 设计并导出了数据库到 MySQL Workbench）上”这一部分。好像crebas.sql这个文件是没有的

### ISSUE THREAD

**Issue by seekerhuang** [hewei2001/campus-canteen-ordering#3]

**Comment by hewei2001** [comment]
你好，PowerDesigner 可以认为只是一个用来「设计」数据库结构的工具，例如文章中写到的 PDM，就是由其绘制。此后 PowerDesigner 可以导出一个 crebas.sql 文件用于创建 MySQL 数据库。

需要注意的是，本文中创建 MySQL 数据库后，又将其反向导入到了 Django 项目中（见 models.py），接下来的工作都是在 models.py 中设计的。因此，你可以认为 crebas.sql 文件在复现本项目的过程中是「不必要」的，所以我没有提供。

如果你还是想要，可以留下一个邮箱，我过后发给你。

**Comment by seekerhuang** [comment]
> 你好，PowerDesigner 可以认为只是一个用来「设计」数据库结构的工具，例如文章中写到的 PDM，就是由其绘制。此后 PowerDesigner 可以导出一个 crebas.sql 文件用于创建 MySQL 数据库。
> 
> 需要注意的是，本文中创建 MySQL 数据库后，又将其反向导入到了 Django 项目中（见 models.py），接下来的工作都是在 models.py 中设计的。因此，你可以认为 crebas.sql 文件在复现本项目的过程中是「不必要」的，所以我没有提供。
> 
> 如果你还是想要，可以留下一个邮箱，我过后发给你。

2249147450@qq.com,非常感谢！
